In [42]:
#Task
import numpy as np
arr1d=np.random.randint(1,100,size=10)
print(f"1D Array is: \t\t\t{arr1d}")
add=arr1d+3
print(f"Addition with 3 is: \t\t{add}")
sub=arr1d-2
print(f"Subtraction with 2 is: \t\t{sub}")
mul=arr1d*5
print(f"Multiplication with 5 is: \t{mul}")
div=np.array(arr1d/2,dtype=float)
print(f"Division by 2 is: \t\t{div}")
slice1=arr1d[2:7] # slice 5 numbers
print(f"Slicing 5 numbers are: \t\t{slice1}")
print(f"Last 3 numbers are: \t\t{arr1d[-3:]}")


1D Array is: 			[69 40 49 94 46 33 38 95 77 96]
Addition with 3 is: 		[72 43 52 97 49 36 41 98 80 99]
Subtraction with 2 is: 		[67 38 47 92 44 31 36 93 75 94]
Multiplication with 5 is: 	[345 200 245 470 230 165 190 475 385 480]
Division by 2 is: 		[34.5 20.  24.5 47.  23.  16.5 19.  47.5 38.5 48. ]
Slicing 5 numbers are: 		[49 94 46 33 38]
Last 3 numbers are: 		[95 77 96]


In [45]:
arr_ones = np.ones((2, 3))  # Creates a 2x3 array of ones
print("Array of ones:")
print(arr_ones)
print(arr_ones.shape)


Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [57]:
#Task
arr1=np.array(["Bob","Alice","Simson","Charlie"])
print(arr1)
arr1=np.append(arr1,"Kane") #Append a name in last
print(arr1)
arr1=np.insert(arr1,2,"Braylon") # insert a name at index 2
print(arr1)
arr2=np.array(["Sierra","Dean","Amelie","Martin","Yousef"])
print(arr2)
arr3=np.concatenate((arr1,arr2)) # combine both arrays
print(arr3)

['Bob' 'Alice' 'Simson' 'Charlie']
['Bob' 'Alice' 'Simson' 'Charlie' 'Kane']
['Bob' 'Alice' 'Braylon' 'Simson' 'Charlie' 'Kane']
['Sierra' 'Dean' 'Amelie' 'Martin' 'Yousef']
['Bob' 'Alice' 'Braylon' 'Simson' 'Charlie' 'Kane' 'Sierra' 'Dean'
 'Amelie' 'Martin' 'Yousef']


In [73]:
#Task
arr1=np.arange(1,5)
print(arr1)
arr1=np.append(arr1,10) # append a number in last
print(arr1)
arr1=np.insert(arr1,3,10) #insert number at index 3
print(arr1)
print(f"Maximum is {arr1.max()} at index {arr1.argmax()}")
print(f"Minimum is {arr1.min()} at index {arr1.argmin()}")
arr2=np.arange(11,17)
print(arr2)
print(f"Addition of two arrays are: {arr1+arr2}")
arr3=np.concatenate((arr1,arr2)) # combine both arrays
print(arr3)

[1 2 3 4]
[ 1  2  3  4 10]
[ 1  2  3 10  4 10]
Maximum is 10 at index 3
Minimum is 1 at index 0
[11 12 13 14 15 16]
Addition of two arrays are: [12 14 16 24 19 26]
[ 1  2  3 10  4 10 11 12 13 14 15 16]
