In [2]:
str3="raza"
print(f"test { str3}")

test raza


In [6]:
!pip install scikit-learn


     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.6 kB 435.7 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/60.6 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 322.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.6 MB 3.2 MB/s eta 0:00:04
   ---------------------------------------- 0.1/10.6 MB 3.2 MB/s eta 0:00:04
   ---------------------------------------- 0.1/10.6 MB 871.5 kB/s eta 0:00:13
   ---------------------------------------- 0.1/10.6 MB 901.1 kB/s eta 0:00:12
    --------------------------------------- 0.2/10.6 MB 952.6 kB/s eta 0:00:11
    ----------

In [7]:
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv("tv_shows.csv")

In [27]:
df.dropna(inplace=True)

In [36]:
# Create a DataFrame from the value counts
year_counts = df["Year"].value_counts().reset_index()
#year_counts.columns = ["Year", "Count"]
year_counts


Year  count
0   2018    111
1   2019    108
2   2017    100
3   2016     87
4   2015     87
5   2020     59
6   2014     50
7   2013     48
8   2011     33
9   2009     30
10  2012     27
11  2010     24
12  2007     18
13  2006     17
14  2005     17
15  2008     16
16  2004     14
17  2001     10
18  1999     10
19  2003      9
20  1995      8
21  1998      6
22  1993      6
23  2002      6
24  1992      5
25  2000      4
26  1997      4
27  1969      2
28  1988      2
29  1990      2
30  1989      2
31  1991      2
32  1981      1
33  1978      1
34  1963      1
35  1959      1
36  1966      1
37  1987      1
38  1964      1

In [37]:
# Reshape the data
X = year_counts["Year"].values.reshape(-1, 1)  # Independent variable (Year)
X

array([[2018],
       [2019],
       [2017],
       [2016],
       [2015],
       [2020],
       [2014],
       [2013],
       [2011],
       [2009],
       [2012],
       [2010],
       [2007],
       [2006],
       [2005],
       [2008],
       [2004],
       [2001],
       [1999],
       [2003],
       [1995],
       [1998],
       [1993],
       [2002],
       [1992],
       [2000],
       [1997],
       [1969],
       [1988],
       [1990],
       [1989],
       [1991],
       [1981],
       [1978],
       [1963],
       [1959],
       [1966],
       [1987],
       [1964]], dtype=int64)

In [39]:
# Reshape the data
Y = year_counts["count"].values  # Dependent variable (Count)
Y

array([111, 108, 100,  87,  87,  59,  50,  48,  33,  30,  27,  24,  18,
        17,  17,  16,  14,  10,  10,   9,   8,   6,   6,   6,   5,   4,
         4,   2,   2,   2,   2,   2,   1,   1,   1,   1,   1,   1,   1],
      dtype=int64)

In [40]:
model=LinearRegression()
model.fit(X,Y)

LinearRegression()

In [47]:
year_2024 = np.array([[2450]])
predicted_count=model.predict(year_2024)
predicted_count


array([629.17915351])

In [49]:
X=np.array([[2010],[2011],[2012],[2013],[2014],[2015], [2016], [2017], [2018], [2019], [2020], [2021],[2022],[2023],[2024]])

In [50]:
Y=np.array([0.09, 0.30,5.28,13.30,754.22, 314.25,434.33, 998.33, 13657.20,3843.52, 7200.17, 29374.15,47686.81, 16625.08, 44167.33])

In [51]:
model.fit(X,Y)

LinearRegression()

In [58]:
pre=model.predict(np.array([[2027]]))
pre

array([39733.15983333])

In [73]:
#from sklearn.linear_model import LinearRegression
#from sklearn.preprocessing import PolynomialFeatures
from sklearn import *
model=linear_model.LinearRegression()
feature=preprocessing.PolynomialFeatures(degree=3) #degree=2


In [79]:
X=np.array([[6],[7],[8],[9]])
#Y=np.array([36,49,64,81]) # Square
Y=np.array([216,343,512,729]) # Cube

In [80]:
X_ploy=feature.fit_transform(X)

In [81]:
model.fit(X_ploy,Y)

LinearRegression()

In [82]:
X_new_poly=feature.transform(np.array([[4]]))
predict=model.predict(X_new_poly)
predict

array([64.])

In [83]:
from sklearn.svm import SVR

In [84]:
# linear equation Y=2X+3
X=np.array([[1], [2], [3], [4], [5]])

In [85]:
Y=np.array([5, 7, 9, 11, 13]) # Y=2X+3

In [87]:
svm_regressor=SVR(kernel='linear')
svm_regressor.fit(X,Y)

SVR(kernel='linear')

In [88]:
predicted=svm_regressor.predict(np.array([[6]]))
predicted

array([14.85])