In [1]:
!pip install scikit-learn

In [3]:
import numpy as np

In [5]:
X = np.array([
    [85, 3.6],
    [70, 3.2],
    [60, 2.8],
    [45, 2.5],
    [95, 3.9],
    [80, 3.4],
    [55, 3.0],
    [65, 3.1],
    [75, 3.3],
    [90, 3.7]
])
X


array([[85. ,  3.6],
       [70. ,  3.2],
       [60. ,  2.8],
       [45. ,  2.5],
       [95. ,  3.9],
       [80. ,  3.4],
       [55. ,  3. ],
       [65. ,  3.1],
       [75. ,  3.3],
       [90. ,  3.7]])

In [7]:
Y = np.array(['A+', 'B', 'C-', 'D+', 'A', 'B+', 'C', 'C+', 'B-', 'A-'])
Y


array(['A+', 'B', 'C-', 'D+', 'A', 'B+', 'C', 'C+', 'B-', 'A-'],
      dtype='<U2')

In [10]:
from sklearn import tree
#from sklearn.dataset import load_iris
#from sklearn.model_selection import train_test_split

In [13]:
clf=tree.DecisionTreeClassifier()
clf.fit(X,Y)

DecisionTreeClassifier()

In [14]:
predicted_Grade = clf.predict([[85, 3.8]])
print(predicted_Grade)

['A+']


In [15]:
predicted_Grade = clf.predict([[50, 2.7]])
print(predicted_Grade)

['C']


In [16]:
X=np.array([[4,1], [6,2], [8,3], [11,4], [15,5], [18,6]]) #Feature [['Anniversary Year','Number of Children']]
X

array([[ 4,  1],
       [ 6,  2],
       [ 8,  3],
       [11,  4],
       [15,  5],
       [18,  6]])

In [23]:
Y=np.array([70,65,55,50,45,40]) #Label ['Remaining Life']
Y

array([70, 65, 55, 50, 45, 40])

# Using Linear Regression


In [30]:
from sklearn.linear_model import LinearRegression

In [24]:
model_linear=LinearRegression()
model_linear.fit(X,Y)

LinearRegression()

In [29]:
print(f"Predicted Remaining Life using Linear Regression Model: {model_linear.predict([[22,8]])}")

Predicted Remaining Life using Linear Regression Model : [24.69230769]


# Using SVM

In [31]:
from sklearn.svm import SVR

In [33]:
svm_regressor=SVR(kernel='linear')
svm_regressor.fit(X,Y)

SVR(kernel='linear')

In [34]:
print(f"Predicted Remaining Life using SVM: {svm_regressor.predict([[22,8]])}")

Predicted Remaining Life using SVM: [28.66]


# Using DecisionTree

In [35]:
from sklearn import tree

In [36]:
clf=tree.DecisionTreeClassifier()
clf.fit(X,Y)

DecisionTreeClassifier()

In [37]:
print(f"Predicted Remaining Life using Decision Tree: {clf.predict([[22,8]])}")

Predicted Remaining Life using Decision Tree: [40]
