In [1]:
from abc import ABC, abstractmethod

class Animal(ABC):  # Abstract base class
    def __init__(self, name):
        self.name = name

    @abstractmethod
    def sound(self):  # Abstract method
        pass

class Dog(Animal):
    def sound(self):  # Implementation of abstract method
        return "Woof!"

class Cat(Animal):
    def sound(self):  # Implementation of abstract method
        return "Meow!"

# Instantiate concrete classes
dog = Dog("Buddy")
cat = Cat("Whiskers")

# Call methods
print(dog.sound())  # Output: Woof!
print(cat.sound())  # Output: Meow!


Woof!
Meow!


NumPy, short for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for multidimensional arrays, along with a collection of functions to operate on these arrays efficiently. NumPy is the cornerstone for many other Python libraries in scientific computing and data analysis because of its powerful array processing capabilities.

Here's a brief introduction to some of the key features and concepts in NumPy:

1. **Arrays**: NumPy's primary object is the `ndarray` (N-dimensional array). It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. NumPy arrays can have any number of dimensions and are homogeneously typed.

2. **Array Creation**: You can create NumPy arrays in several ways, such as from Python lists or using built-in functions like `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`, etc.

3. **Array Operations**: NumPy provides a wide range of mathematical functions that operate element-wise on arrays. These include arithmetic operations, trigonometric functions, exponential and logarithmic functions, and more. NumPy also allows for broadcasting, which enables operations between arrays of different shapes.

4. **Indexing and Slicing**: NumPy arrays support advanced indexing techniques, including slicing, fancy indexing, and boolean indexing, which allow for efficient data manipulation and extraction.

5. **Shape Manipulation**: NumPy provides functions to change the shape, size, and structure of arrays. You can reshape arrays, concatenate arrays, split arrays, and transpose arrays easily.

6. **Broadcasting**: NumPy's broadcasting rules allow for arithmetic operations between arrays of different shapes. Broadcasting automatically aligns dimensions to perform element-wise operations efficiently.

7. **Linear Algebra**: NumPy provides a rich set of functions for linear algebra operations, including matrix multiplication, eigenvalue decomposition, singular value decomposition, solving linear equations, and more.

8. **Random Number Generation**: NumPy includes a powerful random number generation module (`np.random`) that allows you to generate random numbers from various probability distributions.

9. **Integration with other Libraries**: NumPy seamlessly integrates with other scientific computing libraries like SciPy (for advanced mathematical functions and scientific computation), Matplotlib (for plotting and visualization), Pandas (for data manipulation and analysis), and more.

Simple example demonstrating the creation of a NumPy array and some basic operations:

```python
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)

# Array arithmetic operations
arr_sum = arr1d + 10
print("Array Addition:", arr_sum)

# Array slicing
print("Sliced Array:", arr1d[1:4])
```

This is just a brief overview of NumPy's capabilities. It is a vast library with many more functionalities for scientific computing and data manipulation. If you're interested in learning more, the NumPy documentation and various tutorials available online are excellent resources.

Creating NumPy arrays using various methods:

1. **From a Python List**: You can create a NumPy array from a Python list using the `np.array()` function.
2. **Using Built-in Functions**: NumPy provides several built-in functions to create arrays with specific properties, such as zeros, ones, and empty arrays.
3. **Using Random Number Generation**: NumPy's random module (`np.random`) allows you to create arrays filled with random numbers from different probability distributions.

**Methods:**

```python
import numpy as np

# 1. From a Python List
arr_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr_from_list)

# 2. Using Built-in Functions
# Create an array of zeros
arr_zeros = np.zeros(5)  # Creates a 1D array of zeros with length 5
print("Array of zeros:", arr_zeros)

# Create a 2D array of ones
arr_ones = np.ones((2, 3))  # Creates a 2x3 array of ones
print("Array of ones:")
print(arr_ones)

# Create an empty array
arr_empty = np.empty(3)  # Creates a 1D array of uninitialized (random) values with length 3
print("Empty array:", arr_empty)

# 3. Using Random Number Generation
# Create an array of random integers between 0 and 9
arr_random_int = np.random.randint(0, 10, size=5)  # Creates a 1D array of 5 random integers
print("Array of random integers:", arr_random_int)

# Create a 2D array of random floats between 0 and 1
arr_random_float = np.random.rand(2, 3)  # Creates a 2x3 array of random floats
print("Array of random floats:")
print(arr_random_float)
```

In this example:

- We create NumPy arrays from Python lists using `np.array()`.
- We use built-in functions like `np.zeros()`, `np.ones()`, and `np.empty()` to create arrays with specific properties.
- We generate arrays filled with random numbers using `np.random.randint()` and `np.random.rand()`.

These methods provide flexibility in creating NumPy arrays tailored to your specific needs. You can adjust the dimensions, data types, and properties of the arrays based on your requirements.

Some common array attributes and methods in NumPy:

1. **reshape()**: Reshapes the array into a new shape.
2. **max()**: Returns the maximum value in the array.
3. **min()**: Returns the minimum value in the array.
4. **argmax()**: Returns the indices of the maximum value in the array.
5. **argmin()**: Returns the indices of the minimum value in the array.
6. **shape**: Returns the shape of the array.
7. **dtype**: Returns the data type of the elements in the array.
8. **size**: Returns the total number of elements in the array.
9. **ndim**: Returns the number of dimensions of the array.

Let's see these attributes and methods in action:

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
arr_reshaped = arr.reshape(2, 3)
print("Reshaped array:")
print(arr_reshaped)

# Find maximum value in the array
max_value = arr.max()
print("Maximum value:", max_value)

# Find minimum value in the array
min_value = arr.min()
print("Minimum value:", min_value)

# Find indices of maximum and minimum values
argmax_index = arr.argmax()
argmin_index = arr.argmin()
print("Index of maximum value:", argmax_index)
print("Index of minimum value:", argmin_index)

# Get the shape of the array
array_shape = arr.shape
print("Shape of array:", array_shape)

# Get the data type of the elements in the array
data_type = arr.dtype
print("Data type of array elements:", data_type)

# Get the total number of elements in the array
array_size = arr.size
print("Total number of elements in the array:", array_size)

# Get the number of dimensions of the array
array_ndim = arr.ndim
print("Number of dimensions of the array:", array_ndim)
```

In this example, we create a 1D array and demonstrate the usage of various attributes and methods. We reshape the array, find its maximum and minimum values, get their indices, retrieve the shape, data type, size, and number of dimensions of the array.

Common operations on NumPy arrays:

1. **Copying Arrays**: Creating copies of arrays to manipulate independently.
2. **Appending Elements**: Adding elements to the end of an array.
3. **Inserting Elements**: Inserting elements at specified positions in an array.
4. **Sorting**: Sorting the elements of an array.
5. **Removing/Deleting Elements**: Removing elements from an array.
6. **Combining/Concatenating Arrays**: Combining multiple arrays into a single array.
7. **Splitting Arrays**: Splitting a single array into multiple arrays.

Let's see how these operations can be performed:

```python
import numpy as np

# Original array
arr1 = np.array([1, 2, 3, 4, 5])

# 1. Copying Arrays
arr2 = arr1.copy()
print("Copied array:", arr2)

# 2. Appending Elements
arr3 = np.append(arr1, 6)
print("Array after appending element:", arr3)

# 3. Inserting Elements
arr4 = np.insert(arr1, 2, 10)  # Insert 10 at index 2
print("Array after inserting element:", arr4)

# 4. Sorting
arr5 = np.array([3, 1, 4, 2, 5])
arr5_sorted = np.sort(arr5)
print("Sorted array:", arr5_sorted)

# 5. Removing/Deleting Elements
arr6 = np.delete(arr1, 2)  # Delete element at index 2
print("Array after deleting element:", arr6)

# 6. Combining/Concatenating Arrays
arr7 = np.array([6, 7, 8])
arr_combined = np.concatenate((arr1, arr7))
print("Combined array:", arr_combined)

# 7. Splitting Arrays
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_split = np.split(arr8, [3, 6])  # Split at indices 3 and 6
print("Split arrays:", arr_split)
```

In this example, we demonstrate each operation on a sample array `arr1`. We create copies of the array, append and insert elements, sort the array, delete elements, combine arrays, and split arrays into multiple parts.

These operations are fundamental in manipulating and working with arrays efficiently in NumPy.

Loading and saving data is a common task in data analysis and machine learning workflows. NumPy provides functions for efficiently loading and saving data in various formats, such as text files, binary files, and NumPy's own `.npy` format.

Here's how you can load and save data using NumPy:

1. **Loading Data**:
   - `numpy.loadtxt()`: Load data from a text file.
   - `numpy.genfromtxt()`: Load data from a text file with missing values handled gracefully.
   - `numpy.load()`: Load data from a `.npy` file.

2. **Saving Data**:
   - `numpy.savetxt()`: Save data to a text file.
   - `numpy.savetxt()`: Save data to a text file with specified formatting options.
   - `numpy.save()`: Save data to a `.npy` file.

Let's see examples of loading and saving data:

```python
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. Saving Data
# Save data to a text file
np.savetxt('data.txt', data)

# Save data to a text file with specified delimiter and formatting options
np.savetxt('data_custom.txt', data, delimiter=',', fmt='%d')

# Save data to a .npy file
np.save('data.npy', data)

# 2. Loading Data
# Load data from a text file
loaded_data_txt = np.loadtxt('data.txt')
print("Loaded data from text file:")
print(loaded_data_txt)

# Load data from a text file with specified delimiter
loaded_data_custom_txt = np.loadtxt('data_custom.txt', delimiter=',')
print("Loaded data from custom text file:")
print(loaded_data_custom_txt)

# Load data from a .npy file
loaded_data_npy = np.load('data.npy')
print("Loaded data from .npy file:")
print(loaded_data_npy)
```

In this example:
- We first create a sample NumPy array `data`.
- We save this data to a text file using `np.savetxt()`, with default and custom formatting options, and to a `.npy` file using `np.save()`.
- We then load the saved data using `np.loadtxt()` and `np.load()`.

These functions provide a convenient way to handle data loading and saving tasks in NumPy. Depending on your specific needs and the nature of your data, you can choose the appropriate function and format for efficient data handling.

In [12]:
import numpy as np

# Sample data
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. Saving Data
# Save data to a text file
np.savetxt('data.txt', data)

# Save data to a text file with specified delimiter and formatting options
np.savetxt('data_custom.txt', data, delimiter=',', fmt='%d')

# Save data to a .npy file
np.save('data.npy', data)

# 2. Loading Data
# Load data from a text file
loaded_data_txt = np.loadtxt('data.txt')
print("Loaded data from text file:")
print(loaded_data_txt)

# Load data from a text file with specified delimiter
loaded_data_custom_txt = np.loadtxt('data_custom.txt', delimiter=',')
print("Loaded data from custom text file:")
print(loaded_data_custom_txt)

# Load data from a .npy file
loaded_data_npy = np.load('data.npy')
print("Loaded data from .npy file:")
print(loaded_data_npy)


Loaded data from text file:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Loaded data from custom text file:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Loaded data from .npy file:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Indexing and selection in NumPy allow you to access specific elements, rows, or columns of arrays based on their indices or certain conditions. This is a fundamental aspect of working with NumPy arrays, especially when dealing with multidimensional arrays.

Here's how you can perform indexing and selection in NumPy:

1. **Indexing a 2D Array**: Accessing elements, rows, and columns of a 2D array using integer indices.
2. **Logical Selection**: Selecting elements of an array based on certain conditions using boolean arrays.

Let's see examples for both:

```python
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1. Indexing a 2D Array
# Accessing individual elements
print("Element at row 1, column 2:", arr_2d[1, 2])

# Accessing entire rows or columns
print("First row:", arr_2d[0])
print("Second column:", arr_2d[:, 1])  # Note the use of : to select entire column

# 2. Logical Selection
# Creating a boolean array based on a condition
bool_array = arr_2d > 5
print("Boolean array based on condition:")
print(bool_array)

# Selecting elements based on the boolean array
selected_elements = arr_2d[bool_array]
print("Selected elements based on condition:", selected_elements)
```

In this example:

- We create a sample 2D array `arr_2d`.
- For indexing, we access individual elements using integer indices (`arr_2d[1, 2]`), entire rows (`arr_2d[0]`), and entire columns (`arr_2d[:, 1]`).
- For logical selection, we create a boolean array based on a condition (elements greater than 5), and then use this boolean array to select elements from the original array.

Indexing and selection are powerful features in NumPy that enable you to manipulate arrays efficiently and perform various operations based on specific criteria. Understanding these concepts is essential for effective data manipulation and analysis using NumPy.

Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined in arithmetic operations. Broadcasting typically occurs when performing arithmetic operations between arrays of different shapes, enabling NumPy to handle operations efficiently and intuitively.

Here's how broadcasting works in NumPy:

1. **Shape Compatibility**: Broadcasting begins with comparing the shapes of the arrays being operated on. The arrays must be compatible, meaning that their shapes should either be equal or compatible according to certain rules.

2. **Dimensions**: If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on its leading (left) side to match the number of dimensions of the larger array.

3. **Size Compatibility**: After aligning the shapes, the sizes of corresponding dimensions are compared. Two dimensions are compatible if they are equal or if one of them is 1. If neither condition is met, NumPy raises a ValueError.

4. **Broadcasting**: Once the arrays' shapes are compatible, NumPy automatically broadcasts the arrays' values across the appropriate dimensions to perform the operation efficiently.

Here's an example demonstrating broadcasting:

```python
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])

# Shape of arr1: (2, 3)
# Shape of arr2: (2, 1)

# Broadcasting: arr2's shape is broadcasted to match arr1's shape
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result of broadcasting:")
print(result)
```

In this example:

- We have two arrays, `arr1` of shape (2, 3) and `arr2` of shape (2, 1).
- Due to broadcasting rules, the shape of `arr2` is broadcasted to (2, 3) to match the shape of `arr1`.
- The operation `arr1 + arr2` adds corresponding elements of `arr1` and `arr2` element-wise, resulting in a new array of shape (2, 3).

Broadcasting simplifies many operations in NumPy, making it easier to perform arithmetic operations on arrays of different shapes without having to explicitly reshape or duplicate data. Understanding broadcasting is crucial for writing concise and efficient NumPy code.

In [13]:
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10], [20]])

# Shape of arr1: (2, 3)
# Shape of arr2: (2, 1)

# Broadcasting: arr2's shape is broadcasted to match arr1's shape
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result of broadcasting:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[10]
 [20]]
Result of broadcasting:
[[11 12 13]
 [24 25 26]]


Type casting, also known as type conversion, is the process of converting data from one data type to another. In Python, type casting is typically done using constructor functions or using the `astype()` method for NumPy arrays.

Here's how you can perform type casting in Python:

1. **Using Constructor Functions**: For built-in data types like int, float, str, etc., you can use constructor functions to explicitly convert data to the desired type.

```python
# Integer to float
x = 10
y = float(x)
print(y)  # Output: 10.0

# Float to integer
x = 10.5
y = int(x)
print(y)  # Output: 10

# String to integer
x = "10"
y = int(x)
print(y)  # Output: 10
```

2. **Using `astype()` method in NumPy**: For NumPy arrays, you can use the `astype()` method to convert the data type of the array elements.

```python
import numpy as np

# Create an array of integers
arr_int = np.array([1, 2, 3, 4, 5])

# Convert array to float
arr_float = arr_int.astype(float)
print(arr_float)

# Convert array to string
arr_str = arr_int.astype(str)
print(arr_str)
```

Type casting is useful when you need to perform operations that require operands of compatible types or when you need to ensure that the data is in the appropriate format for further processing. Keep in mind that type casting may result in loss of precision or information, especially when converting between data types with different representations or ranges. Therefore, it's essential to understand the implications of type casting in your code and handle it appropriately.

In Python, you can perform arithmetic operations such as addition (+), subtraction (-), multiplication (*), division (/), exponentiation (**), and modulus (%) on numerical data types like integers and floats. These operations are straightforward and can be applied to both individual numbers and arrays (in the case of NumPy).

Here's how you can perform arithmetic operations in Python:

```python
# Addition
result_addition = 10 + 5
print("Addition:", result_addition)  # Output: 15

# Subtraction
result_subtraction = 10 - 5
print("Subtraction:", result_subtraction)  # Output: 5

# Multiplication
result_multiplication = 10 * 5
print("Multiplication:", result_multiplication)  # Output: 50

# Division
result_division = 10 / 5
print("Division:", result_division)  # Output: 2.0 (float division)

# Exponentiation
result_exponentiation = 10 ** 2
print("Exponentiation:", result_exponentiation)  # Output: 100

# Modulus (Remainder)
result_modulus = 10 % 3
print("Modulus:", result_modulus)  # Output: 1 (remainder of division 10/3)
```

In addition to basic arithmetic operations, you can also perform these operations on arrays in NumPy:

```python
import numpy as np

# Create NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Array Addition
arr_addition = arr1 + arr2
print("Array Addition:", arr_addition)  # Output: [5 7 9]

# Array Subtraction
arr_subtraction = arr2 - arr1
print("Array Subtraction:", arr_subtraction)  # Output: [3 3 3]

# Array Multiplication
arr_multiplication = arr1 * arr2
print("Array Multiplication:", arr_multiplication)  # Output: [ 4 10 18]

# Array Division
arr_division = arr2 / arr1
print("Array Division:", arr_division)  # Output: [4.  2.5 2. ]

# Array Exponentiation
arr_exponentiation = arr1 ** 2
print("Array Exponentiation:", arr_exponentiation)  # Output: [1 4 9]

# Array Modulus
arr_modulus = arr2 % 3
print("Array Modulus:", arr_modulus)  # Output: [1 2 0]
```

These operations are fundamental in Python programming and are commonly used in mathematical calculations, data manipulation, and scientific computing.

Universal functions (ufuncs) in NumPy are functions that operate element-wise on arrays, meaning they apply a function to each element of an array independently. These functions are implemented in compiled C code and are highly optimized for performance, making them very efficient for large arrays.

Here are some common universal functions in NumPy:

1. **Mathematical Functions**: `np.sin()`, `np.cos()`, `np.tan()`, `np.exp()`, `np.log()`, `np.sqrt()`, etc.
2. **Trigonometric Functions**: `np.sin()`, `np.cos()`, `np.tan()`, `np.arcsin()`, `np.arccos()`, `np.arctan()`, etc.
3. **Exponential and Logarithmic Functions**: `np.exp()`, `np.log()`, `np.log10()`, `np.log2()`, etc.
4. **Rounding Functions**: `np.round()`, `np.floor()`, `np.ceil()`, etc.
5. **Absolute Value**: `np.abs()`
6. **Comparison Functions**: `np.equal()`, `np.not_equal()`, `np.greater()`, `np.greater_equal()`, `np.less()`, `np.less_equal()`, etc.
7. **Statistical Functions**: `np.mean()`, `np.median()`, `np.std()`, `np.var()`, `np.sum()`, `np.min()`, `np.max()`, etc.
8. **Logical Functions**: `np.logical_and()`, `np.logical_or()`, `np.logical_xor()`, `np.logical_not()`, etc.
9. **Array Manipulation Functions**: `np.reshape()`, `np.transpose()`, `np.flatten()`, etc.
10. **Random Number Generators**: `np.random.rand()`, `np.random.randn()`, `np.random.randint()`, etc.

Here's how you can use some of these universal functions:

```python
import numpy as np

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Math functions
print("Sin:", np.sin(arr))
print("Exp:", np.exp(arr))
print("Sqrt:", np.sqrt(arr))

# Statistical functions
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Sum:", np.sum(arr))

# Logical functions
print("Greater than 3:", np.greater(arr, 3))
print("Logical AND with condition:", np.logical_and(arr > 2, arr < 5))

# Random number generator
print("Random array:", np.random.rand(5))
```

These universal functions provide a convenient way to perform various operations on arrays efficiently in NumPy. They simplify the syntax and make the code more concise and readable.

In [14]:
import numpy as np

# Mathematical Functions
arr = np.array([0, np.pi/4, np.pi/2])
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))
print("tan:", np.tan(arr))
print("exp:", np.exp(arr))
print("log:", np.log(arr + 1))
print("sqrt:", np.sqrt(arr))

# Trigonometric Functions
arr = np.array([0, 0.5, 1])
print("arcsin:", np.arcsin(arr))
print("arccos:", np.arccos(arr))
print("arctan:", np.arctan(arr))

# Exponential and Logarithmic Functions
arr = np.array([1, 10, 100])
print("log10:", np.log10(arr))
print("log2:", np.log2(arr))

# Rounding Functions
arr = np.array([1.1, 1.6, 2.3])
print("round:", np.round(arr))
print("floor:", np.floor(arr))
print("ceil:", np.ceil(arr))

# Absolute Value
arr = np.array([-1, -2, 3])
print("abs:", np.abs(arr))

# Comparison Functions
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
print("equal:", np.equal(arr1, arr2))
print("not_equal:", np.not_equal(arr1, arr2))
print("greater:", np.greater(arr1, arr2))
print("greater_equal:", np.greater_equal(arr1, arr2))
print("less:", np.less(arr1, arr2))
print("less_equal:", np.less_equal(arr1, arr2))

# Statistical Functions
arr = np.array([1, 2, 3, 4, 5])
print("mean:", np.mean(arr))
print("median:", np.median(arr))
print("std:", np.std(arr))
print("var:", np.var(arr))
print("sum:", np.sum(arr))
print("min:", np.min(arr))
print("max:", np.max(arr))

# Logical Functions
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, False])
print("logical_and:", np.logical_and(arr1, arr2))
print("logical_or:", np.logical_or(arr1, arr2))
print("logical_xor:", np.logical_xor(arr1, arr2))
print("logical_not:", np.logical_not(arr1))

# Array Manipulation Functions
arr = np.array([[1, 2], [3, 4]])
print("reshape:", np.reshape(arr, (1, 4)))
print("transpose:", np.transpose(arr))
print("flatten:", arr.flatten())

# Random Number Generators
print("random.rand:", np.random.rand(3))
print("random.randn:", np.random.randn(3))
print("random.randint:", np.random.randint(1, 10, 3))


sin: [0.         0.70710678 1.        ]
cos: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
tan: [0.00000000e+00 1.00000000e+00 1.63312394e+16]
exp: [1.         2.19328005 4.81047738]
log: [0.         0.57964145 0.94421571]
sqrt: [0.         0.88622693 1.25331414]
arcsin: [0.         0.52359878 1.57079633]
arccos: [1.57079633 1.04719755 0.        ]
arctan: [0.         0.46364761 0.78539816]
log10: [0. 1. 2.]
log2: [0.         3.32192809 6.64385619]
round: [1. 2. 2.]
floor: [1. 1. 2.]
ceil: [2. 2. 3.]
abs: [1 2 3]
equal: [False  True  True]
not_equal: [ True False False]
greater: [False False False]
greater_equal: [False  True  True]
less: [ True False False]
less_equal: [ True  True  True]
mean: 3.0
median: 3.0
std: 1.4142135623730951
var: 2.0
sum: 15
min: 1
max: 5
logical_and: [False False False]
logical_or: [ True  True  True]
logical_xor: [ True  True  True]
logical_not: [False  True False]
reshape: [[1 2 3 4]]
transpose: [[1 3]
 [2 4]]
flatten: [1 2 3 4]
random.rand: [0.27057951 0.